# Generated by Django 3.0.8 on 2020-07-05 21:02

from django.db import migrations, models
import django.db.models.deletion
import webApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(help_text='Maximum file size allowed is 1Mb', max_length=30, upload_to=webApp.models.path_and_rename_logo, validators=[webApp.models.validate_logo_image])),
                ('clubState', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('image', models.ImageField(help_text='Maximum file size allowed is 2Mb', max_length=30, upload_to='path_and_rename_player', validators=[webApp.models.validate_player_image])),
                ('jerseyNumber', models.IntegerField()),
                ('Country', models.CharField(max_length=30)),
                ('matches', models.IntegerField()),
                ('run', models.IntegerField()),
                ('highest', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='webApp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('team', models.ManyToManyField(related_name='matches_count', to='webApp.Team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='webApp.Team')),
            ],
        ),
    ]
