# Generated by Django 3.0.8 on 2020-07-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20200706_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='points',
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('team', models.ManyToManyField(related_name='points_team', to='webApp.Team')),
            ],
        ),
    ]
