# Generated by Django 3.0.8 on 2020-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_auto_20200707_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
